# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\"-\n\x05MyReq\x12\x11\n\tint_param\x18\x01 \x01(\x05\x12\x11\n\tstr_param\x18\x02 \x01(\t\")\n\x06MyResp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2+\n\x06MyGrpc\x12!\n\x0cGetSomething\x12\x06.MyReq\x1a\x07.MyResp\"\x00\x62\x06proto3'
)




_MYREQ = _descriptor.Descriptor(
  name='MyReq',
  full_name='MyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_param', full_name='MyReq.int_param', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='str_param', full_name='MyReq.str_param', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=59,
)


_MYRESP = _descriptor.Descriptor(
  name='MyResp',
  full_name='MyResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='MyResp.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='MyResp.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['MyReq'] = _MYREQ
DESCRIPTOR.message_types_by_name['MyResp'] = _MYRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyReq = _reflection.GeneratedProtocolMessageType('MyReq', (_message.Message,), {
  'DESCRIPTOR' : _MYREQ,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:MyReq)
  })
_sym_db.RegisterMessage(MyReq)

MyResp = _reflection.GeneratedProtocolMessageType('MyResp', (_message.Message,), {
  'DESCRIPTOR' : _MYRESP,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:MyResp)
  })
_sym_db.RegisterMessage(MyResp)



_MYGRPC = _descriptor.ServiceDescriptor(
  name='MyGrpc',
  full_name='MyGrpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=104,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSomething',
    full_name='MyGrpc.GetSomething',
    index=0,
    containing_service=None,
    input_type=_MYREQ,
    output_type=_MYRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MYGRPC)

DESCRIPTOR.services_by_name['MyGrpc'] = _MYGRPC

# @@protoc_insertion_point(module_scope)
