# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class MyGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSomething = channel.unary_unary(
                '/MyGrpc/GetSomething',
                request_serializer=test__pb2.MyReq.SerializeToString,
                response_deserializer=test__pb2.MyResp.FromString,
                )


class MyGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSomething(self, request, context):
        """なにかを受け取るRPC（xx_pb2_proto.pyのコメントとして使用される）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSomething': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSomething,
                    request_deserializer=test__pb2.MyReq.FromString,
                    response_serializer=test__pb2.MyResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MyGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSomething(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MyGrpc/GetSomething',
            test__pb2.MyReq.SerializeToString,
            test__pb2.MyResp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
